### ISSUE TITLE
[feature] 문자열 입력과 숫자 추출 및 더하기 기능 구현 

### ISSUE THREAD

**Issue by kanghanju** [kanghanju/java-calculator-7#1]
## TODO 

- [ ] 문자열을 입력 받는다.

- [ ] 입력한 문자열에서 숫자를 추출해 더한다.
    - [ ] 쉼표 또는 콜론을 구분자로 갖는 문자열을 입력 받을 경우 구분자를 기준으로 분리 한다. 
    - [ ] 커스텀 구분자를 기준으로 문자열을 분리한다.
